import ErrorDisplay from "components/ErrorDisplay"
import Game from "components/Game"
import useField from "hooks/useField"
import { useSession } from "next-auth/react"
import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"
import { addGame } from "services/games"
import styles from "./styles.module.scss"

export default function AddGame() {
  const name = useField({ type: "text" })
  const gameCover = useField({ type: "text" })
  const studio = useField({ type: "text" })
  const gameYear = useField({ type: "number" })
  const steamLink = useField({ type: "text" })
  const [error, setError] = useState("")
  const [showCover, setShowCover] = useState("/PlaceHolder.jpg")
  const router = useRouter()
  const { data: session } = useSession()
  useEffect(() => {
    if (!session || session.user.group !== "Admin") router.replace("/games")
  })

  const handleSubmit = async (e) => {
    e.preventDefault()
    const data = {
      name: name.input.value,
      gameCover: gameCover.input.value,
      studio: studio.input.value,
      gameYear: gameYear.input.value,
      steamLink: steamLink.input.value,
      completed: false,
    }
    try {
      await addGame(data)
      router.push("/games")
    } catch ({ response }) {
      setError(response.data.error.message || response.data.error)
    }
  }

  const handleShow = (e) => {
    e.preventDefault()
    if (
      gameCover.input.value.startsWith("http://") ||
      gameCover.input.value.startsWith("https://")
    ) {
      setShowCover(gameCover.input.value)
    }
  }

  return (
    <section>
      <Head>
        <title>Add game to collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorDisplay text={error} />
      <form onSubmit={handleSubmit} className={styles.form}>
        <div>
          <label name="name">game name:</label>
          <input {...name.input} placeholder="Name" name="name" />
        </div>
        <div>
          <label>game cover:</label>
          <input
            {...gameCover.input}
            placeholder="Game Cover Link"
            name="gameCover"
          />
        </div>
        <div>
          <label name="studio">studio:</label>
          <input {...studio.input} placeholder="Name" name="studio" />
        </div>
        <div>
          <label name="Game year">game year:</label>
          <input {...gameYear.input} placeholder="Year" name="Game year" />
        </div>
        <div>
          <label name="Steam link">steam link:</label>
          <input {...steamLink.input} placeholder="Link" name="Steam link" />
        </div>
        <div>
          <button onClick={handleShow} className={styles.button}>
            Show Cover
          </button>
          <button type="submit" className={styles.button}>
            Upload
          </button>
        </div>
      </form>
      <article>
        <Game
          name={name.input.value}
          gameCover={showCover}
          studio={studio.input.value}
          gameYear={gameYear.input.value}
          steamLink={steamLink.input.value}
        ></Game>
      </article>
    </section>
  )
}
