import Head from "next/head"
import Image from "next/image"

const data = {
  name: "Pokemon",
  cover: "/PlaceHolder.jpg",
  state: "Dropeada",
  sinopsis:
    "El anime de Pokémon es uno de los pocos que es basado en un videojuego debido a la popularidad de este. La historia del anime esta centrada en un chico de 10 años llamado Ash Ketchum. Este muchacho tiene el sueño de llegar a ser el mejor entrenador Pokémon del mundo. La historia empieza exactamente la noche anterior a que este muchacho empezara su viaje. Este chico vive en Pueblo Paleta con su madre (del padre no se sabe nada). En este pueblo también vive una autoridad del mundo Pokémon, el Profesor Oak, quien le entrega a todos los nuevos entrenadores su primer Pokémon y una herramienta llamada Pokedex (una enciclopedia de alta tecnología con información sobre todos los Pokémon), es esta persona quien le da su primer Pokémon a Ash, como ustedes bien sabrán, un Pikachu.",
  genres: ["action", "aventuras", "comedia", "fantasía", "seinen"],
  comentary: "Explican todo como si fueramos idiotas",
  score: 6.9,
  season: "winter",
  watched: 25,
  year: 1995,
}

export default function Ph() {
  return (
    <section>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>{data.name}</h1>
      </header>
      <article>
        <section>
          <Image
            src={data.cover}
            alt={`${data.name} cover`}
            width={250}
            height={320}
          />
        </section>
        <section>
          <h2>generos:</h2>
          <ul>
            {data.genres.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
          <p>{data.genres}</p>
          <h2>temporada:</h2>
          <p>
            {data.season} {data.year}
          </p>
          <h2>episodios:</h2>
          <p>{data.episodes ? data.episodes : "?"}</p>
          <h2>sinopsis:</h2>
          <p>{data.sinopsis}</p>
        </section>
      </article>
      <article>
        <h2>estado:</h2>
        <p>{data.state}</p>
        <h2>episodios vistos:</h2>
        <p>
          {data.watched} / {data.episodes ? data.episodes : "?"}
        </p>
        <h2>comentario:</h2>
        <p>{data.comentary}</p>
        <h2>score:</h2>
        <p>{data.score}</p>
      </article>
    </section>
  )
}
