const games = [
  {
    name: "Hunie Cam Studio",
    status: "finished",
    order: 1,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Slay The Spire",
    status: "finished",
    order: 2,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Dark Fear",
    status: "finished",
    order: 3,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Kirby's Adventure in Dreamland Advance",
    status: "finished",
    order: 4,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "S.C.A.R.S.",
    status: "finished",
    order: 5,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Grimm's Hollow",
    status: "finished",
    order: 6,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Helltaker",
    status: "finished",
    order: 7,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Sonic The Hedgehog",
    status: "finished",
    order: 8,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Final Fantasy V",
    status: "finished",
    order: 9,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Prince of Persia: Sands of Time",
    status: "finished",
    order: 10,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Prince of Persia: The Warrior Within",
    status: "finished",
    order: 11,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Prince of Persia: Two Crowns",
    status: "finished",
    order: 12,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Momodora",
    status: "finished",
    order: 13,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
  {
    name: "Final Fantasy VI",
    status: "on progress",
    order: 14,
    gameCover: "placeHolder",
    creators: "ph",
    gameYear: 1995,
  },
]

export default function handler(req, res) {
  res.status(200).json(games)
}
