import Head from "next/head"

export default function Radio() {
  return (
    <article>
      <Head>
        <title>Invernalia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Radio</h1>
    </article>
  )
}
