import Head from "next/head"
import { useEffect, useState } from "react"
import Game from "components/Game"
import styles from "pages/games/styles.module.scss"

export default function Games() {
  const [games, setGames] = useState([])
  useEffect(() => {
    fetch("/api/games")
      .then((res) => res.json())
      .then(setGames)
  }, [])
  return (
    <section className={styles.background}>
      <Head>
        <title>Juegos de ROM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={styles.title}>Games</h1>
        <p className={styles.description}>
          Here is a list of the games played by RoM
        </p>
      </header>
      <section>
        <ul className={styles.list}>
          {games
            .sort((a, b) => b.order - a.order)
            .map(
              ({
                order,
                name,
                completed,
                gameCover,
                studio,
                gameYear,
                steamLink,
              }) => {
                return (
                  <li key={order}>
                    <Game
                      order={order}
                      name={name}
                      completed={completed}
                      gameCover={gameCover}
                      studio={studio}
                      gameYear={gameYear}
                      steamLink={steamLink}
                    />
                  </li>
                )
              }
            )}
        </ul>
      </section>
    </section>
  )
}
